[book]
authors = ["Félix Saparelli"]
language = "en"
multilingual = false
src = "src"
title = "Félix Saparelli"

[preprocessor.toc]
renderer = ["html"]
marker = "* auto-gen TOC;\n{:toc}"
max-level = 4

[output.html]
cname = "passcod.name"
git-repository-url = "https://github.com/passcod/blook"
curly-quotes = true
mathjax-support = true

[output.html.fold]
enable = true
level = 1

[output.linkcheck]
